### ISSUE TITLE
Show us how to add Handlebars in real life

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/js-templates-advanced-templating-readme#2]
I am working on my rails with JQuery front end project right now and am trying to use what I learned in these Handlebars lessons; however, in these lessons, Handlebars was pre-loaded in the program for us and I have spent a ridiculous amount time trying to figure out how to add Handlebars to a regular Rails program. I'm not recommending it needs to go in this specific lesson, but would be helpful if there were a reference in some lesson.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback this feedback, @dtow55.

This lesson and the related templating lessons will be reviewed for accuracy, clarity and relevance to the learning goals we have set for our JavaScript coursework. We will be updating these materials in an upcoming JavaScript update.

Thank you for contributing to a learn.co repository!. 💙
