### ISSUE TITLE
These two labs seem very rushed and confusing

### ISSUE THREAD

**Issue by dannyenfp** [learn-co-curriculum/js-templates-advanced-templating-readme#3]
I think you should have broken down these labs a bit more... I am taking way too long on both of these labs and it's very confusing. 

I think there should be about 3 labs and maybe 1-2 reading sections on this. I imagine I could get this done faster if it was paced correctly. It seems ridiculous to have us do complicated forms from the get-go, rather than build up our confidence with Handlebars. Not useful.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback this feedback, @dannyenfp .

This issue has been documented as a known issue and will be resolved in an upcoming JS update. This lesson and the related templating lessons will be reviewed for accuracy, clarity and relevance to the learning goals we have set for our JavaScript coursework. 

Thank you for contributing to a learn.co repository!. 💙
